services:
  tinyRAG:
    image: tinyrag:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GRADIO_LISTEN=true
      - GRADIO_SERVER_PORT=8080
      - REST_API_LISTEN=true
      - REST_API_PORT=8000
